stages:
  - sonarqube-check
  - sonarqube-vulnerability-report

sonarqube-check:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ${CI_PROJECT_DIR}/.sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - RollMaster_backendcode_phase2

sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=ACSPHP_2815_mobelapp_AYw026NoAhxV3SDlr-_p&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: false
  only:
    - RollMaster_backendcode_phase2
  artifacts:
    expire_in: 1 day
    reports:
      sast: ${CI_PROJECT_DIR}/gl-sast-sonar-report.json
  dependencies:
    - sonarqube-check
